# Generated by Django 4.2.5 on 2024-10-02 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lib.utils
import machinery.mixins.channels
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, machinery.mixins.channels.ChannelMixin),
        ),
        migrations.CreateModel(
            name='ChatSessionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=lib.utils.get_upload_path)),
                ('name', models.CharField(max_length=255)),
                ('favorite', models.BooleanField(blank=True, default=False, null=True)),
                ('vectorized', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='ChatSessionMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pipeline', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('valid', models.BooleanField(blank=True, null=True)),
                ('selected', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('request', 'requête'), ('response', 'réponse'), ('error', 'erreur')])),
                ('renderer', models.CharField(default='markdown', max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=32)),
                ('token', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='core.chatsessionmessage')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='core.userpreference')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicPipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('generate_media', models.BooleanField(default=False)),
                ('input', models.CharField(choices=[('text', 'texte'), ('image', 'image'), ('sound', 'son'), ('audio', 'audio'), ('music', 'musique'), ('summary', 'résumé'), ('file', 'fichier'), ('file list', 'liste de fichiers'), ('text/image', 'texte/image'), ('text/file', 'texte/fichier')], max_length=255)),
                ('output', models.CharField(choices=[('text', 'texte'), ('image', 'image'), ('sound', 'son'), ('audio', 'audio'), ('music', 'musique'), ('summary', 'résumé'), ('file', 'fichier'), ('file list', 'liste de fichiers'), ('text/image', 'texte/image'), ('text/file', 'texte/fichier')], max_length=255)),
                ('factory', models.CharField(max_length=255)),
                ('params', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('ready', models.BooleanField(default=True)),
                ('user_can_read', models.BooleanField(default=False)),
                ('user_can_write', models.BooleanField(default=False)),
                ('user_can_update', models.BooleanField(default=False)),
                ('user_can_delete', models.BooleanField(default=False)),
                ('group_can_read', models.BooleanField(default=False)),
                ('group_can_write', models.BooleanField(default=False)),
                ('group_can_update', models.BooleanField(default=False)),
                ('group_can_delete', models.BooleanField(default=False)),
                ('other_can_read', models.BooleanField(default=False)),
                ('other_can_write', models.BooleanField(default=False)),
                ('other_can_update', models.BooleanField(default=False)),
                ('other_can_delete', models.BooleanField(default=False)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_pipelines', to='auth.group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_pipelines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSessionMessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.chatsessionfile')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.chatsessionmessage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='usertoken',
            constraint=models.UniqueConstraint(fields=('user', 'namespace', 'alias'), name='unique_user_namespace_alias'),
        ),
    ]
