from django.conf import settings
from django.utils.translation import gettext as _
from django.utils.functional import classproperty

from ollama import Client

from machinery.pipelines.base import BasePipeline


class OllamaPipeline(BasePipeline):

    MODEL = None
    SYSTEM = None

    def __init__(self, session):
        super(OllamaPipeline, self).__init__(session)

    @classproperty
    def client(cls):
        return Client(host=settings.OLLAMA_BACKEND_URL)

    @classmethod
    def get_default_label(cls):
        label_tpl = _('Generate text using %s')
        return label_tpl % (cls.MODEL,)

    @classmethod
    def get_default_description(cls):
        description_tpl = _('This pipeline will use model %s and Ollama to generate some text')
        return description_tpl % (cls.MODEL,)

    def set_session_title(self, prompt):
        return "Generated by Ollama"
