# Generated by Django 5.0.3 on 2024-10-02 12:51

import core.models
import django.db.models.deletion
import lib.auth
import mptt.fields
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalGroup',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=256)),
                ('groupname', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=150)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('user_can_read', models.BooleanField(default=False)),
                ('user_can_write', models.BooleanField(default=False)),
                ('user_can_update', models.BooleanField(default=False)),
                ('user_can_delete', models.BooleanField(default=False)),
                ('group_can_read', models.BooleanField(default=False)),
                ('group_can_write', models.BooleanField(default=False)),
                ('group_can_update', models.BooleanField(default=False)),
                ('group_can_delete', models.BooleanField(default=False)),
                ('other_can_read', models.BooleanField(default=False)),
                ('other_can_write', models.BooleanField(default=False)),
                ('other_can_update', models.BooleanField(default=False)),
                ('other_can_delete', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('group', models.ForeignKey(null=True, on_delete=models.SET(lib.auth.get_root_group), to='core.externalgroup')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.folder')),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(lib.auth.get_root_user), to='core.externaluser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('content_lang', models.CharField(max_length=3, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('summary', models.TextField(null=True)),
                ('summary_lang', models.CharField(max_length=3, null=True)),
                ('url', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('embedding', pgvector.django.VectorField(dimensions=768, null=True)),
                ('namespace', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to=core.models.get_upload_path)),
                ('context', models.JSONField(blank=True, default=dict, null=True)),
                ('state', models.CharField(choices=[('init', 'Initial'), ('startprocess', 'Processing started'), ('textconverted', 'Converted to text'), ('vectorized', 'Vectorized'), ('finalized', 'Finalized'), ('error', 'Error')], default='init')),
                ('user_can_read', models.BooleanField(default=False)),
                ('user_can_write', models.BooleanField(default=False)),
                ('user_can_update', models.BooleanField(default=False)),
                ('user_can_delete', models.BooleanField(default=False)),
                ('group_can_read', models.BooleanField(default=False)),
                ('group_can_write', models.BooleanField(default=False)),
                ('group_can_update', models.BooleanField(default=False)),
                ('group_can_delete', models.BooleanField(default=False)),
                ('other_can_read', models.BooleanField(default=False)),
                ('other_can_write', models.BooleanField(default=False)),
                ('other_can_update', models.BooleanField(default=False)),
                ('other_can_delete', models.BooleanField(default=False)),
                ('group', models.ForeignKey(null=True, on_delete=models.SET(lib.auth.get_root_group), to='core.externalgroup')),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(lib.auth.get_root_user), to='core.externaluser')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.folder')),
            ],
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.externalgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.externaluser')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('content_lang', models.CharField(max_length=3, null=True)),
                ('embedding', pgvector.django.VectorField(dimensions=768)),
                ('summary', models.TextField(null=True)),
                ('summary_lang', models.CharField(max_length=3, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.document')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineDocumentVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', pgvector.django.VectorField(dimensions=768)),
                ('pipeline', models.CharField(max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.document')),
            ],
        ),
        migrations.CreateModel(
            name='PipelineFolderContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline', models.CharField(max_length=255)),
                ('context', models.JSONField(blank=True, default=dict, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.folder')),
            ],
        ),
    ]
