"""
Django settings for searchapp project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import sys

from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STACK_DIR = BASE_DIR.parent.parent
sys.path.append(str(STACK_DIR))

from lib.config import get_config
config = get_config()

SEARCHAPP_PROTOCOL = config.processes.core.search.settings.protocol
SEARCHAPP_HOSTNAME = config.processes.core.search.settings.hostname
SEARCHAPP_PORT = config.processes.core.search.settings.port
SITE_ROOT = f'{SEARCHAPP_PROTOCOL}://{SEARCHAPP_HOSTNAME}:{SEARCHAPP_PORT}'

BACKEND_PROTOCOL = config.processes.core.backend.settings.protocol
BACKEND_HOSTNAME = config.processes.core.backend.settings.hostname
BACKEND_PORT = config.processes.core.backend.settings.port
BACKEND_URL = f'{BACKEND_PROTOCOL}://{BACKEND_HOSTNAME}:{BACKEND_PORT}'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.common.search_secret or 'keepyoursecretsecret'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # NOSONAR

ALLOWED_HOSTS = []
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = ['http://localhost:8000', 'http://localhost:8081', 'http://localhost:3000']

# Application definition
INSTALLED_APPS = [
    'django_rq',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.TokenAuthenticationMiddleware',
]

ROOT_URLCONF = 'searchapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'searchapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('db_name') or config.processes.core.search.settings.db_name,
        'USER': os.getenv('db_user') or config.processes.core.search.settings.db_user,
        'PASSWORD': os.getenv('db_password') or config.processes.core.search.settings.db_password,
        'HOST': 'localhost',
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = config.common.language_code
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Custom settings

RQ_QUEUES = {
    'search': {
        'HOST': config.common.redis.host or 'localhost',
        'PORT': config.common.redis.port or 6379,
        'DEFAULT_TIMEOUT': config.common.redis.db.timeout or 360,
        'DB': config.common.redis.db.search or 3,
    },
}

SCHEDULER_CONFIG = {
    'EXECUTIONS_IN_PAGE': 20,
    'DEFAULT_RESULT_TTL': 500,
    'DEFAULT_TIMEOUT': 300,  # 5 minutes
    'SCHEDULER_INTERVAL': 2,  # 2 seconds
}


USE_GPU = (os.getenv('use_gpu') or config.processes.core.search.settings.use_gpu) == '1'
PART_SIZE = int(os.getenv('part_size') or config.processes.core.search.settings.part_size)
PART_OVERLAP = int(os.getenv('part_overlap') or config.processes.core.search.settings.part_overlap)

SUMMARY_MODEL = os.getenv('summary_model') or config.processes.core.search.settings.summary_model

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

OLLAMA_BACKEND_URL = config.processes.core.backend.computed.ollama_url

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

CSRF_COOKIE_AGE = config.common.cookie_age

LOCALE_PATHS = ['locale']
